apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stale-arp-fix
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: stale-arp-fix

  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        name: stale-arp-fix
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 10
      containers:
      - name: arp-fix
        image: ghcr.io/containerd/busybox:1.36
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        command: ["/bin/sh"]
        args: 
          - "-c" 
          - "while true; do for IP in $( ip -4 neigh show dev eth1 | grep STALE | awk '{print $1}'); do if ping ${IP} -c 1 -4 -W 1 -q 2>&1 > /dev/null; then echo \"$IP reachable\"; else echo \"$IP unreachable\"; fi; done; sleep 10; done"